-- ==============================================================================
-- Seed Script: supabase/seed.sql
-- Description: Seeds the verified 11 projects from PORTFOLIO_DATA.showcaseProjects
--              into the projects table with accurate attributes and ordering.
-- ==============================================================================

INSERT INTO public.projects (
  type,
  title,
  slug,
  client_name,
  year,
  description,
  preview_image_url,
  video_url,
  video_provider,
  video_id,
  aspect_ratio,
  live_url,
  github_url,
  can_embed,
  tags,
  is_published,
  sort_order,
  published_at
) VALUES
-- 1. Video: Biqolpo
(
  'video',
  'Biqolpo — Latent Stories',
  'biqolpo-latent-stories',
  'Biqolpo',
  '2024–2026',
  'Experimental generative narratives blending synthetic visual concept art with cinematic pacing, AI voiceover mastering, and temporal motion synthesis.',
  '/images/work-1-biqolpo.png',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
  'local',
  NULL,
  '16:9',
  NULL,
  NULL,
  false,
  ARRAY['Google Veo', 'Runway Gen-2', 'DaVinci Resolve', 'AI Compositing'],
  true,
  1,
  '2026-03-01 10:00:00+00'
),
-- 2. Video: Syston Autos
(
  'video',
  'Syston Autos Cinema',
  'syston-autos-cinema',
  'Syston Autos Ltd',
  '2024–2025',
  'High-energy automotive showcase series with precision cut pacing, engine audio enhancement, cinematic color grading, and dynamic motion graphics across 6 episodes.',
  '/images/work-2-syston.png',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
  'local',
  NULL,
  '16:9',
  NULL,
  NULL,
  false,
  ARRAY['Premiere Pro', 'After Effects', 'Sound Design', 'Color Grading'],
  true,
  2,
  '2026-03-02 10:00:00+00'
),
-- 3. Video: Kinetic Motion
(
  'video',
  'Kinetic Motion & Type System',
  'kinetic-motion-type-system',
  'Creative Studio',
  '2024',
  'Expressive kinetic typography showcase exploring tempo modulation, bold typographic layouts, synchronized beat drops, and geometric motion design.',
  '/images/work-3-web.png',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
  'local',
  NULL,
  '16:9',
  NULL,
  NULL,
  false,
  ARRAY['After Effects', 'Kinetic Typography', 'Motion Graphics', 'Beat Sync'],
  true,
  3,
  '2026-03-03 10:00:00+00'
),
-- 4. Video: Nocturne Cinema
(
  'video',
  'Nocturne Cinema & Soundscapes',
  'nocturne-cinema-soundscapes',
  'Independent Cinema',
  '2023–2024',
  'Moody atmospheric narrative piece emphasizing dialogue clarity, layered ambient foley, tonal color grades, and evocative textural cuts.',
  '/images/work-4-it.png',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
  'local',
  NULL,
  '16:9',
  NULL,
  NULL,
  false,
  ARRAY['DaVinci Resolve', 'Sound Design', 'Atmospheric Foley', 'Color Grading'],
  true,
  4,
  '2026-03-04 10:00:00+00'
),
-- 5. Video: B&F Cars (9:16 Vertical Reel)
(
  'video',
  'B&F Cars Automotive',
  'bf-cars-automotive',
  'B&F Cars',
  '2024–2025',
  'Fast-paced social media reels and showroom presentations featuring speed ramping, kinetic typography, vehicle feature highlights, and multi-platform vertical exports.',
  '/images/work-5-bfcars.png',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
  'local',
  NULL,
  '9:16',
  NULL,
  NULL,
  false,
  ARRAY['CapCut Pro', 'Premiere Pro', 'Motion Graphics', '9:16 Vertical Reel'],
  true,
  5,
  '2026-03-05 10:00:00+00'
),
-- 6. Web: Flux Capital
(
  'web',
  'Flux Capital',
  'flux-capital',
  'Emblem',
  '2026',
  'Flux Capital empowers innovative startups with strategic funding and expert guidance for digital success.',
  '/images/aurexa/aurexa-project-1.png',
  NULL,
  NULL,
  NULL,
  '16:9',
  'https://react.dev',
  'https://github.com/kamrul-islam-dev',
  false,
  ARRAY['React.js', 'TypeScript', 'Tailwind CSS', 'REST APIs'],
  true,
  1,
  '2026-03-06 10:00:00+00'
),
-- 7. Web: Boltshift X
(
  'web',
  'Boltshift X',
  'boltshift-x',
  'Boltshift',
  '2026',
  'Boltshift X empowers brands with innovative design solutions to enhance their digital presence and achieve remarkable growth.',
  '/images/aurexa/aurexa-project-2.png',
  NULL,
  NULL,
  NULL,
  '16:9',
  'https://kamrulislam.bd',
  'https://github.com/kamru1i/portfolio',
  true,
  ARRAY['Next.js', 'TypeScript', 'Framer Motion', 'Tailwind CSS'],
  true,
  2,
  '2026-03-07 10:00:00+00'
),
-- 8. Web: Flux Labs
(
  'web',
  'Flux Labs',
  'flux-labs',
  'Flux Studio',
  '2026',
  'Flux Labs specializes in innovative design solutions that empower brands to thrive and distinguish themselves online.',
  '/images/aurexa/aurexa-project-3.png',
  NULL,
  NULL,
  NULL,
  '16:9',
  'https://wordpress.org',
  NULL,
  false,
  ARRAY['WordPress', 'PHP / MySQL', 'Elementor Pro', 'DNS / SSL'],
  true,
  3,
  '2026-03-08 10:00:00+00'
),
-- 9. Web: Orbital Systems
(
  'web',
  'Orbital Systems',
  'orbital-systems',
  'Orbital',
  '2024',
  'Orbital Systems delivers unified design engineering, precision design tokens, and robust digital ecosystems for enterprise brands.',
  '/images/aurexa/aurexa-project-4.png',
  NULL,
  NULL,
  NULL,
  '16:9',
  'https://cloudflare.com',
  'https://github.com/kamrul-islam-dev',
  false,
  ARRAY['Cloudflare', 'DNS Routing', 'SSL/TLS', 'Security Shield'],
  true,
  4,
  '2026-03-09 10:00:00+00'
),
-- 10. Web: Flora & Fauna
(
  'web',
  'Flora & Fauna',
  'flora-fauna',
  'Flora',
  '2026',
  'Flora & Fauna delivers bespoke e-commerce architecture and immersive product storytelling tailored for modern lifestyle brands.',
  '/images/aurexa/aurexa-project-5.png',
  NULL,
  NULL,
  NULL,
  '16:9',
  'https://react.dev',
  'https://github.com/kamrul-islam-dev',
  false,
  ARRAY['Next.js', 'E-Commerce', 'Stripe', 'Tailwind CSS'],
  true,
  5,
  '2026-03-10 10:00:00+00'
),
-- 11. Web: Solaris Energy
(
  'web',
  'Solaris Energy',
  'solaris-energy',
  'Emblem',
  '2026',
  'Solaris Energy harnesses the sun''s power to provide sustainable, innovative solutions for a brighter future.',
  '/images/aurexa/aurexa-project-6.png',
  NULL,
  NULL,
  NULL,
  '16:9',
  'https://react.dev',
  'https://github.com/kamrul-islam-dev',
  false,
  ARRAY['Clean Energy', 'UI Systems', 'TypeScript', 'Performance'],
  true,
  6,
  '2026-03-11 10:00:00+00'
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  client_name = EXCLUDED.client_name,
  year = EXCLUDED.year,
  preview_image_url = EXCLUDED.preview_image_url,
  video_url = EXCLUDED.video_url,
  video_provider = EXCLUDED.video_provider,
  aspect_ratio = EXCLUDED.aspect_ratio,
  live_url = EXCLUDED.live_url,
  github_url = EXCLUDED.github_url,
  can_embed = EXCLUDED.can_embed,
  tags = EXCLUDED.tags,
  is_published = EXCLUDED.is_published,
  sort_order = EXCLUDED.sort_order,
  published_at = EXCLUDED.published_at;
